#!/bin/bash

###########################################################################
# common
IP=172.17.88.10
MASK=24
GATEWAY=172.17.42.1
VERSION=


INDEX=1
CI_SERVER_URL=http://172.17.88.9/
REGISTRATION_TOKEN=60a3700088fdb572d3c4
VOLUME_DATA=$HOME/appstore/tfs/runner-gitlab/data
###########################################################################

VERSION=${VERSION:-"latest"};

if [ $# -lt 1 ]; then
    echo "Usage: tfs-runner-gitlab run|start|stop|clean";
    exit 0;
fi

# 启动容器
function start_docker {
    sudo docker start tfs-runner-gitlab-$INDEX;
    sudo pipework docker0 tfs-runner-gitlab-$INDEX $IP/$MASK@$GATEWAY;
}

# 停止容器
function stop_docker {
    sudo docker stop tfs-runner-gitlab-$INDEX;
}

# 创建容器+初始化+启动容器
function run_docker {
    #
    # 这里的--link名称别名必须是postgresql redisio
    #
    echo "run docker using image[hary/gitlab-ci] version[$VERSION]";
    sudo docker run -i -t -d --name=tfs-runner-gitlab-$INDEX --hostname=tfs-runner-gitlab-$INDEX \
    -e "CI_SERVER_URL=$CI_SERVER_URL" \
    -e "REGISTRATION_TOKEN=$REGISTRATION_TOKEN" \
    -v $VOLUME_DATA:/home/gitlab_ci_runner/data \
    hary/runner-gitlab:$VERSION;

    sudo pipework docker0 tfs-runner-gitlab-$INDEX $IP/$MASK@$GATEWAY;
    echo "IP address is[$IP/$MASK] and gateway[$GATEWAY]";
}


#####################################################################################
# main
#####################################################################################
case $1 in
   # create container and initialize it and running
   run) run_docker;;

   # docker start
   start) start_docker;;

   # docker stop_docker
   stop) stop_docker;;

    # clean volume data
   clean) sudo rm -fr $VOLUME_DATA/* $VOLUME_LOG/* ;;
esac

